### ISSUE TITLE
Update the webpage

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/atn-docs#2]
I've committed a few changes per #1 

How do we reflect those changes on the website?

After I build the environment locally following the README, I receive the following error when running `make livehtml`:
```
>make livehtml
Running Sphinx v5.1.1
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).

Sphinx error:
Builder name livehtml not registered or available through entry point
```

**Comment by kwilcox** [comment]
`livehtml` fixed in https://github.com/ioos/atn-docs/commit/6a3b24804650e20fce5364958eff3b985c1a5536
